<!DOCTYPE html>
<html>
<?php $this->render("_head.phtml"); ?>
<body>
<main>
    <section>
        <h1>404 - Brain not found</h1>
        <p>Page you are looking for was not found :/</p>
        <p>Try to do one of following things:</p>
        <ul>
            <li>Get back to the previous page and refresh it</li>
            <li>Make sure you didn't make a typo (i.e. <i>ww.dupa</i> instead of <i>www.dupa</i>).</li>
            <li>You could been hacked! Run away from home.</li>
        </ul>
    </section>
</main>
<?php $this->render("_footer.phtml"); ?>
</body>
</html>