
<footer>
    <div class="small">
        <section>
            <p>Stuff</p>
            <p>Stuff</p>
            <p>Stuff</p>
            <p>Stuff</p>
            <p>Stuff</p>
        </section>
    </div>
    <div class="strong">
        <section class="clear">
            <div class="author">Copyright &copy; 2015 | Daniel Wilkowski</div>
            <div class="logo"></div>
            <div class="clear">
                <ul class="menu clear">
                    <li>Home</li>
                    <li>Calc</li>
                    <li>About delta</li>
                </ul>
            </div>
        </section>
    </div>
</footer>