
<footer>
    <div class="small">
        <section>
            <p>Stuff</p>
            <p>Stuff</p>
            <p>Stuff</p>
            <p>Stuff</p>
            <p>Stuff</p>
        </section>
    </div>
    <div class="strong">
        <section class="clear">
            <div class="author">Copyright &copy; 2015 | Daniel Wilkowski</div>
            <div class="logo"></div>
            <div>
                <ul class="menu clear">
                    <li><a href="?page=home">Home</a></li>
                    <li><a href="?page=author">Author</a></li>
                    <li><a href="?page=about">About delta</a></li>
                </ul>
            </div>
        </section>
    </div>
</footer>